### PR TITLE
Management refactor

### PR DESCRIPTION
**Pull request by bengreenberg5**
- change the config standard from INI to YAML
- add new hyperpameters (see `open_map.yaml`)
- specify run name, config path, and # iterations in CLI args

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
- must save checkpoints
- then fix `record_video.py`

**Comment by quinn-dougherty** [comment]
TODO
- add environment.render method (it's much like board.render)
- wandb integration (with gym.Monitor)

**Comment by RedTachyon** [comment]
```
hyperparameter_defaults = dict(
    gamma=0.99,
    eta=0.0,
    seed=0
)

wandb.init(project="<project-name>",
           name="<run-name>",
           entity="marl-cpr",
           sync_tensorboard=True,
           monitor_gym=True,
           config=hyperparameter_defaults)

config = wandb.config
```

**Comment by bengreenberg5** [comment]
- python learn.py --name single-agent-test --config configs/single_agent.yaml --iters 500 --checkpoint_freq 10

- python record_video_ray.py --config configs/single_agent.yaml --checkpoint_path ~/ray_results/PPO/.../checkpoint-500/checkpoint-500

**Comment by RedTachyon** [comment]
Does the video recording component work? In that case I think this can be merged, if nothing else then to make it a bit more tidy w.r.t. branches

**Pull request merged**
